### ISSUE TITLE
Implement a remote file browser

### ISSUE THREAD

**Issue by PaoloMasci** [thehogfather/pvsio-web#190]

**Comment by thehogfather** [comment]
a bit more description is needed here. For instance a typical use case scenario.

**Comment by PaoloMasci** [comment]
The remote file browser provides functions for browsing directories and opening files (write, rename, or delete operations are NOT needed; ideally a quick preview would be good). It is meant to be used only when the PVSio-web server is executed on localhost. The reason for implementing a remote file browser on localhost is to improve the interaction when opening files in the model editor or in emuchart, or when importing images or pvs files when creating new projects. The main issue with the default file browser we are currently using is that the initial folder from which the file browser starts is handled by the web browser, and so we can't set the initial folder to a convenient location (e.g., the pvsio-web/examples directory).
