### ISSUE TITLE
widget names not loaded when prototype builder panel is collapsed

### ISSUE THREAD

**Issue by PaoloMasci** [thehogfather/pvsio-web#192]
The alpha branch is affected by this bug the first time the tool is executed.

To reproduce the bug:
1. restart the pvsio-web client (i.e., refresh the page in the browser)
2. collapse the prototype builder panel
3. open any project

The error I have in the console is:
Uncaught TypeError: Cannot read property 'selectAll' of undefined (imagemapper.js:147)

The stack trace is
imagemapper.js:147
createRegionimagemapper.js:220
restoreRectRegionWidgetManager.js:106 
(anonymous function)WidgetManager.js:100 WidgetManager.restoreWidgetDefinitionsPrototypeBuilder.js:129 
(anonymous function)WidgetManager.js:183 WidgetManager.updateMapCreator.imageMapper.onReadyimagemapper.js:265 
loadImageimagemapper.js:261

Bug confirmed under Linux, with the latest versions of Chrome and Firefox (Chrome Version 41.0.2272.101 64bits, and Firefox 37.0 64bits)

TODO: add a Jasmine test to test the presence of this bug.

**Comment by PaoloMasci** [comment]
The same bug is also confirmed in branch master.

**Comment by thehogfather** [comment]
This is a very good fix that potentially reduces the complexity of the polling aspect of the imagemapper. I'll do some test push an update.

**Comment by thehogfather** [comment]
@PaoloMasci when you get some time could you test the latest version on alpha and merge to master? All is working as expected on safari, ff and chrome (macosx)
