### ISSUE TITLE
Rendering issue with overlay areas in Prototype Builder

### ISSUE THREAD

**Issue by PaoloMasci** [thehogfather/pvsio-web#194]
Overlay areas are rendered incorrectly in Prototype Builder when saving a project. To reproduce the bug:

* Create a new project (choose a prototype image, no need to select a pvs model)
* Create a display area
* Save the project --> the display area will be resized / moved. If the saved project is re-opened, however, the widget is then shown in the correct position.

**Comment by thehogfather** [comment]
@PaoloMasci I am unable to reproduce this bug on Chrome (OSX). I'm guessing you are on Ubuntu? What browser are you using and can you also tell me the resolution so that I can test on my VM?

**Comment by PaoloMasci** [comment]
Must have been due to local (uncommited) changes on my laptop -- the online versions are not affected by this bug.
