### ISSUE TITLE
[Issue] renaming new transition

### ISSUE THREAD

**Issue by saulors** [thehogfather/pvsio-web#210]
When createding a transition, with this tool selected from the toolbox, then renaming a transiton, and dragging the renaming dialog elsewhere, sometimes the pointer is distant from the dialog blue bar and we can`t separate the cursor from the dialog title bar, so there`s no way to go out of the rename dialog because you can`t reach Rename or Cancel buttons, once the cursor is stuck with the dialog (chrome, osx);

**Comment by PaoloMasci** [comment]
Problem fixed introducing a mouseout event that releases the dialog window when the mouse leaves the panel heading area.
