### ISSUE TITLE
[issue] User Interface Picture in New project

### ISSUE THREAD

**Issue by saulors** [thehogfather/pvsio-web#211]
[Issue] When creating a new project, defining the User Interface Picture in the New Project dialog and clicking [ok] does not bring the image to the new project, it is necessary to load the image from the Prototype builder. The environment: installed in /opt/pvisio-web, user owns the directory and sub-directories, project image is in ~/Desktop (so it is necessary to edit the path and type the user directory); the tool reads the directory and and informs that in a console message. (chrome, osx)

**Comment by PaoloMasci** [comment]
Happens when creating a new project with a picture but without a PVS file. The bug was due to incorrect chaining of Promises.
