### ISSUE TITLE
[Issue] Model editor: sometimes cant click in "compile" button

### ISSUE THREAD

**Issue by saulors** [thehogfather/pvsio-web#212]
Sometimes, when trying to compile some alteration in the statecharts, the "compile" button does not click, even checking if the PVS file is selected; it is necessary to reload the page in order to back to normal (chrome, osx).

**Comment by PaoloMasci** [comment]
The div of the prototype builder was covering the buttons of the model editor. This was happening when changing the zoom level of the page suing the zoom function of the web browser. Forcing the height of the prototype builder div at 100% seems to have fixed the problem.
